dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
env:
  - VERSION=1.0
install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-tests.txt
script: make test
before_deploy:
  - make before-dist version=${VERSION}.${TRAVIS_BUILD_NUMBER}
deploy:
  provider: pypi
  username: __token__
  password:
    secure: "sZHGhUYwPIfXVJAwx1ePOaOP77CC7YFa/7+TNJuNPX+0iRLaWTor8SDuZmGZrxLeHZWU0nOUv6CbQ8SVvr78yFaCdV/TODdQ+lULl8D3wuI2YkMNMeBpzvwUIoSJwgbcY78D2f1A15FkZy4/JLn3fdc9OrRkaRN7MRYWLH22Qfi6tzIvNPdOByNpILKXW0vw3RvsfaHYtxxcXR/tL7YVWtU5ieQzdkKNnSb/9LC2Mrr2z42PS9SxUP/yax6AeTeSbRrHx0+7gWn1FsDRdiSIZm2dPhoZutYgMlhhrfiE4JNzdZ7ZuQQz3tBH+JqzfgqjA47VLMfMaA4D7YY/Ko+MwF3NgkwSPXmTqeEPhchUrG8ybhttiCywe2sE+rKsXD+vj5oRVm/mzL1HGUIZtSX2Ojnh3rZgUk7bRxjFF1wH8jqXXOi+g8598/kzmUDmjWgdTacHsSJEyzf+XVbGlHlgwBrjyog6cDypYt/u4eYLzeSCJQN2ZCkraIlrnyrKlrWru2F4OuzQ2KexdmL022/jn0I5RfgA917Jka+VrVYa5FFnaCKA+A1NUbXSicNG2mgfsUq42XgB00V1qFZUNNWqkUPdwyqtuS4BL3Q1+GM5ZROcyHiAP4FGjG2f4Suvc4InnMDTd0NBwi0zuOz3pbKCCxX5JSeXRKyMfLtYDrNJHI4="
  edge: true
  distributions: sdist bdist_wheel
  on:
    repo: hellofresh/eks-rolling-update
    branch: master
